new css and dark mode
lucgiffon/discorss pull request #26
Opened 2023-02-08 15:55 UTC by LG33

A tester en vrai avant de publier ;)

2023-02-10 21:38 UTC, lucgiffon commented on website/static/style.css
> +    --main-color: #3b6ad9;
Je trouve que le site est beaucoup plus avenant et j'aime bien ces couleurs.

2023-02-10 22:41 UTC, lucgiffon requested changes
Merci beaucoup pour ta contribution! J'aime vraiment mieux le feeling général, les couleurs, l'ambiance. J'ai relevé quelques petites choses qui me dérangeaient notamment par rapport à la lisibilité de certain éléments mais pas seulement. Comment souhaites tu qu'on procède? Souhaites tu que je prenne le relais pour faire les ajustement que je souhaite?

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +@media (prefers-color-scheme: dark) {
Ca c'est vraiment cool!  :)

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +a:hover {
Cool!

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    font-weight: 400;
J'aimais assez quand la police était plus épaisse. Sans cela, certains critères d'accessibilité ne sont pas remplis: https://webaim.org/resources/contrastchecker/?fcolor=3B6AD9&bcolor=EEEEEE

```suggestion
    font-weight: bold;
```

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    text-align: right;
Est-ce-que tu trouves que c'est plus pratique quand c'est en bas à droite? Je trouve que ca fait un peu bizarre les boutons à droite comme ceci.

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    background-color: var(--light-bg-color);
Pour des raisons de lisibilité, j'aimais aussi les bordures sur ces boutons:
```suggestion
    background-color: var(--light-bg-color);
    border: solid;
    border-color: #a6a6a6;
    border-width: 1px;
```

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +.content, container {
petite typo ici 
```suggestion
.content, .container {
```

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
>      display: grid;
```suggestion
```
du coup ce n'est plus nécessaire

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    content: "←";
Les fleches c'est une super idée, je trouve que celles ci rendent bien
```suggestion
    content: "↩";
```

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    content: "→";
```suggestion
    content: "↪";
```

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +.flair:first-letter {
C'est ceci qui cause la première lettre qui se décroche du reste

2023-02-10 22:41 UTC, lucgiffon commented on website/static/style.css
> +    border-width: 0;
Ici aussi, j'aimais bien la bordure pour la lisibilité:
```suggestion
    border-color: #a6a6a6;
    border-width: 1px;
}
```

2023-02-10 23:03 UTC, LG33 commented
Oui vas y fais les changements :)

La seule réserve que j'ai c'est sur la typo. En tant que dev on aime bien
les typos monospace et on a l'oeil habitué à les lire mais en dehors du
code (où elles marchent très bien) c'est quasiment jamais utilisé parce que
c'est moins lisible. Ça prend un surplus d'espace inutile (points,
virgules, apostrophes) et ça écrase les m.

Je me suis pas mal inspiré de Google search et ils utilisent Arial aussi,
et d'ailleurs c'est aussi la typo officielle du shift et des Shifters.

On Fri, Feb 10, 2023, 23:42 lucgiffon ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Merci beaucoup pour ta contribution! J'aime vraiment mieux le feeling
> général, les couleurs, l'ambiance. J'ai relevé quelques petites choses qui
> me dérangeaient notamment par rapport à la lisibilité de certain éléments.
> Comment souhaites tu qu'on procède? Souhaites tu que je prenne le relais
> pour faire les ajustement que je souhaite?
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103284188>:
>
> >  }
>
>
>
>  * {
>
>      margin: 0;
>
>  }
>
>
>
>  body {
>
> -    font-family: 'Courier New', monospace;
>
> +    font-family: Arial, sans-serif;
>
>
> J'ai une réserve sur la police, j'apprécie assez le style Courier que
> j'avais mis.
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103287366>:
>
> >      text-decoration: none;
>
> -    font-weight: 700;
>
> +    font-weight: 300;
>
> +}
>
> +
>
> +.tip {
>
>
> C'est une super idée le petit tip ! :) Merci!
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103291502>:
>
> >  .grid-item-title > a {
>
> +    display: inline-block;
>
>
> Ceci se comporte de façon inattendue. Je ne sais pas exactement comme ça
> fonctionne mais ça cause un retour à la ligne directement après le "tag"
> quand la ligne de titre est trop longue (sur mobile, lorsque la limite
> horizontale et ). Autre souci: la première lettre du nom du tag se retrouve
> en plus séparée du reste du mot.
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103297370>:
>
> > -    font-weight:400;
>
> +    border-width: 0;
>
> +    color: inherit;
>
> +    background-color: var(--light-bg-color);
>
> +    font-weight:100;
>
> +    border-radius: 20px;
>
> +    padding: 1px 7px;
>
> +    font-size: 0.8em;
>
> +    margin-bottom: 3px;
>
> +}
>
> +
>
> +.flair:first-letter {
>
> +    padding-right: 5px;
>
> +}
>
> +
>
> ***@***.*** (prefers-color-scheme: dark) {
>
>
> Ca c'est vraiment cool! :)
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103298506>:
>
> >  }
>
>
>
> -
>
> +a:hover {
>
>
> Cool!
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103302370>:
>
> >      text-decoration: none;
>
> +    font-weight: 400;
>
>
> J'aimais assez quand la police était plus épaisse. Sans cela, certains
> critères d'accessibilité ne sont pas remplis:
> https://webaim.org/resources/contrastchecker/?fcolor=3B6AD9&bcolor=EEEEEE
> ⬇️ Suggested change
>
> -    font-weight: 400;
>
> +    font-weight: bold;
>
>
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103306076>:
>
> >
>
>  .navigation {
>
> -    text-align: center;
>
> -    font-weight: 600;
>
> -    margin-top: 10px;
>
> -    color: var(--main-color);
>
> +    text-align: right;
>
>
> Est-ce-que tu trouves que c'est plus pratique quand c'est en bas à droite?
> Je trouve que ca fait un peu bizarre les boutons à droite comme ceci.
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103309272>:
>
> >  }
>
>
>
> -.navigation>a {
>
> -    border: solid;
>
> -    border-radius: 10px;
>
> -    border-width: 2px;
>
> -    padding: 3px;
>
> -    border-color: var(--main-color);
>
> +.navigation > a {
>
> +    border-radius: 20px;
>
> +    padding: 8px 20px;
>
> +    background-color: var(--light-bg-color);
>
>
> Pour des raisons de lisibilité, j'aimais aussi les bordures sur ces
> boutons:
> ⬇️ Suggested change
>
> -    background-color: var(--light-bg-color);
>
> +    background-color: var(--light-bg-color);
>
> +    border: solid;
>
> +    border-color: #a6a6a6;
>
> +    border-width: 1px;
>
>
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103311198>:
>
> >      font-size: x-small;
>
>      margin-top: 3px;
>
>  }
>
>
>
> -.grid-item-datepub {
>
> +.content, container {
>
>
> petite typo ici
> ⬇️ Suggested change
>
> -.content, container {
>
> +.content, .container {
>
>
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103311544>:
>
> >  }
>
>
>
>  .container {
>
> -    margin: 5px;
>
> -    /*padding-right: 15px;*/
>
>      display: grid;
>
>
> ⬇️ Suggested change
>
> -    display: grid;
>
>
> du coup ce n'est plus nécessaire
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103317243>:
>
> >      text-decoration: none;
>
> -    color: var(--main-color);
>
> +    color: inherit;
>
> +}
>
> +
>
> +.navigation > a:hover {
>
> +    text-decoration: none !important;
>
> +    opacity: 0.7;
>
> +}
>
> +
>
> +.navigation > a#prev::before {
>
> +    content: "←";
>
>
> Les fleches c'est une super idée, je trouve que celles ci rendent bien
> ⬇️ Suggested change
>
> -    content: "←";
>
> +    content: "↩";
>
>
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103317349>:
>
> > -    color: var(--main-color);
>
> +    color: inherit;
>
> +}
>
> +
>
> +.navigation > a:hover {
>
> +    text-decoration: none !important;
>
> +    opacity: 0.7;
>
> +}
>
> +
>
> +.navigation > a#prev::before {
>
> +    content: "←";
>
> +    margin-right: 10px;
>
> +}
>
> +
>
> +.navigation > a#next::after {
>
> +    content: "→";
>
>
> ⬇️ Suggested change
>
> -    content: "→";
>
> +    content: "↪";
>
>
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103318226>:
>
> > -    border-width: 1px;
>
> -    color: black;
>
> -    border-color: black;
>
> -    background-color: white;
>
> -    font-weight:400;
>
> +    border-width: 0;
>
> +    color: inherit;
>
> +    background-color: var(--light-bg-color);
>
> +    font-weight:100;
>
> +    border-radius: 20px;
>
> +    padding: 1px 7px;
>
> +    font-size: 0.8em;
>
> +    margin-bottom: 3px;
>
> +}
>
> +
>
> +.flair:first-letter {
>
>
> C'est ceci qui cause la première lettre qui se décroche du reste
> ------------------------------
>
> In website/static/style.css
> <https://github.com/lucgiffon/discorss/pull/26#discussion_r1103318980>:
>
> >      border: solid;
>
> -    border-width: 1px;
>
> -    color: black;
>
> -    border-color: black;
>
> -    background-color: white;
>
> -    font-weight:400;
>
> +    border-width: 0;
>
>
> Ici aussi, j'aimais bien la bordure pour la lisibilité:
> ⬇️ Suggested change
>
> -    border-width: 0;
>
> +    border-color: #a6a6a6;
>
> +    border-width: 1px;
>
> +}
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lucgiffon/discorss/pull/26#pullrequestreview-1294079508>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBHDIU5I5AJOGA2GBBMZEDWW2733ANCNFSM6AAAAAAUVN5ANU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-02-11 20:01 UTC, lucgiffon commented
Je préfère vraiment l'esthétique de Courier. Tu as un très bon point pour la lisibilité mais je trouve Arial trop... neutre? 

Si tu souhaites quand même mettre Arial pour le serveur des shifters, on peut imaginer faire une commande du bot pour éditer la police de la page du serveur?

2023-02-12 11:07 UTC, merged